# Generated by Django 5.2.14 on 2026-06-19 06:33

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned announcements appear at the top of the feed.')),
            ],
            options={
                'ordering': ['-is_pinned', '-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('hospital', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 or 12 digits long.', regex='^\\d{10}$|^\\d{12}$')])),
                ('needed_by', models.DateField()),
                ('details', models.TextField(blank=True, help_text='Any additional details, e.g. case number, unit count.')),
                ('is_fulfilled', models.BooleanField(default=False, help_text='Mark check once blood is arranged.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['is_fulfilled', 'needed_by', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(help_text='Enter a 10 or 12-digit mobile number.', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 or 12 digits long.', regex='^\\d{10}$|^\\d{12}$')])),
                ('date_of_birth', models.DateField(help_text='Must be 18 years or older to register.')),
                ('join_date', models.DateField(default=datetime.date.today, help_text='The date the member joined KCYM.')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], help_text='Select blood group.', max_length=3)),
                ('is_active_donor', models.BooleanField(default=True, help_text='Designate if this member is currently active and available to donate blood.')),
                ('last_donation_date', models.DateField(blank=True, help_text='Date of last blood donation.', null=True)),
                ('role', models.CharField(choices=[('EXECUTIVE', 'Executive Committee'), ('MEMBER', 'General Member'), ('PENDING', 'Pending Approval')], default='PENDING', help_text='Role-based permissions level.', max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_and_time', models.DateTimeField()),
                ('location', models.CharField(default='St. Thomas Church, Pulluvazhy', max_length=255)),
                ('is_public', models.BooleanField(default=True, help_text='If checked, this event will be visible to non-members/public.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(blank=True, help_text='Member coordinating this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_and_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('GOING', 'Going'), ('MAYBE', 'Maybe'), ('NOT_GOING', 'Not Going')], default='GOING', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='management.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rsvps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'member')},
            },
        ),
    ]
