# Generated by Django 5.2.14 on 2026-06-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_seed_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('EXECUTIVE', 'Executive Committee'), ('MEMBER', 'General Member'), ('PENDING', 'Pending Approval'), ('PRIEST', 'Priest (Father)'), ('VICAR', 'Assistant Vicar')], default='PENDING', help_text='Role-based permissions level.', max_length=15),
        ),
    ]
