# Generated by Django 5.2.14 on 2026-06-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, help_text='Upload an optional event poster/image.', null=True, upload_to='event_posters/'),
        ),
    ]
