# Generated by Django 5.2.14 on 2026-06-19 07:02

import django.core.validators
import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_event_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, help_text='Upload an optional event poster/image (Max 5MB, JPG/PNG).', null=True, upload_to='event_posters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), management.models.validate_file_size]),
        ),
    ]
