# Generated by Django 5.2.14 on 2026-06-19 07:15

import django.core.validators
import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_event_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload an optional profile photo (Max 5MB).', null=True, upload_to='profile_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), management.models.validate_file_size]),
        ),
    ]
