# Generated by Django 5.2.14 on 2026-06-19 07:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_seed_leaders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g. 2025 - 26 KCYM Committee', max_length=100)),
                ('start_year', models.IntegerField(help_text='E.g. 2025')),
                ('end_year', models.IntegerField(help_text='E.g. 2026')),
                ('is_active', models.BooleanField(default=False, help_text='Mark True if this is the current active committee. Only one committee should be active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_year', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('VICAR', 'Vicar'), ('ASSISTANT_VICAR', 'Assistant Vicar'), ('EXECUTIVE', 'Executive Committee'), ('MEMBER', 'General Member'), ('PENDING', 'Pending Approval')], default='PENDING', help_text='Role-based permissions level.', max_length=15),
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('PRESIDENT', 'President'), ('VICE_PRESIDENT', 'Vice President'), ('SECRETARY', 'Secretary'), ('JOINT_SECRETARY', 'Joint Secretary'), ('TREASURER', 'Treasurer'), ('COMMITTEE_MEMBER', 'Committee Member')], default='COMMITTEE_MEMBER', max_length=30)),
                ('joined_at', models.DateField(default=datetime.date.today)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='management.committee')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'member__first_name'],
                'unique_together': {('committee', 'member')},
            },
        ),
    ]
