# Generated by Django 5.2.14 on 2026-06-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_blooddonor'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonor',
            name='total_donations',
            field=models.PositiveIntegerField(default=0, help_text='Total number of times this donor has donated blood.'),
        ),
        migrations.AddField(
            model_name='member',
            name='total_donations',
            field=models.PositiveIntegerField(default=0, help_text='Total number of times this member has donated blood.'),
        ),
    ]
