# Generated by Django 5.2.14 on 2026-06-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_blooddonor_total_donations_member_total_donations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonor',
            name='total_donations',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Total number of times this donor has donated blood.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='total_donations',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Total number of times this member has donated blood.'),
        ),
    ]
